### ISSUE TITLE
Update "clue/socks-react" to 0.8.1

### ISSUE THREAD

**Issue by djagya** [WyriHaximus/react-guzzle-http-client#8]
Because of the outdated "clue/socks-react" other libs like "react/socket" are also outdated (can't update from 0.4 to 0.7).

**Comment by WyriHaximus** [comment]
@clue Do you want/need help updating `clue/socks-react`?

**Comment by clue** [comment]
What exactly is outdated and requires updating here? Afaict clue/socks-react supports all the latest versions?

**Comment by clue** [comment]
clue/buzz-react will need a number of updates once the new React components are out, so perhaps this may be related?

**Comment by nick4fake** [comment]
@clue wyrihaximus/react-guzzle-http-client requires "clue/socks-react" ~0.4 that restricts all other react components to lower versions as well

**Comment by WyriHaximus** [comment]
@nick4fake IIRC @clue updated it recently so I'll look into updating it during my commute home tonight :+1:

**Comment by nick4fake** [comment]
@WyriHaximus it looks like we also need to update clue/buzz-react, but it has many outdated dependencies. I am working on upgrading it

**Comment by WyriHaximus** [comment]
@nick4fake awesome :+1: !

**Comment by brstgt** [comment]
What's the status here? Is this issue blocked somehow?

**Comment by WyriHaximus** [comment]
@brstgt waiting on https://github.com/clue/php-buzz-react/pull/66
